import "./globals.css";
import UserState from "@/context";
import { Header } from "@/components/mainPage/header";
import { ConfigProvider, Layout, theme } from "antd";

export const metadata = {
  title: "Франчайзер",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider theme={{
          algorithm: theme.darkAlgorithm, components: {
            Table: {
              colorBgContainer: "#444444",
              colorText: "#fff",
              headerBg: "#575757",
              headerColor: "#fff",
            }
          }
        }}>
          <UserState>
            <Layout>
              <Header />
            </Layout>

            <div className="page">
              {children}
            </div>
          </UserState>
        </ConfigProvider>
      </body>
    </html>
  );
}
